# App Info
ios_app_id                                : 1218569739                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Take timestamped photos or select images already in your camera roll and add a timestamp to each image.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Marco Contino                                
your_link                                 : https://marcocontino.com                     
your_city                                 :
email_address                             :
facebook_username                         :   
instagram_username                        :
twitter_username                          : AppsByMarco
github_username                           : Marcoc88
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Configuration Options
    description                           : Current date/time or manually select a date/time <br> Location of the timestamp on the image <br> Color of the timestamp <br> Format of the timestamp <br> Font of the timestamp
    fontawesome_icon_name                 : cog
    
  - title                                 : Siri Shortcuts and 3D Touch
    description                           : Use Siri Shortcuts to quickly take a photo <br> Use Siri Shortcuts to quickly select images from the photo library <br> 3D Touch the app icon to quickly take a photo or select photos from the photo library
    fontawesome_icon_name                 : microphone
    
  - title                                 : Pro Version
    description                           : Upgrade to Timestamp Pro to allow an unlimited selection of images when stamping from the photo library
    fontawesome_icon_name                 : stamp
    
  - title                                 : Privacy Policy
    description                           : <a href="https://marcocontino.com/Timestamp/">Timestamp Privacy Policy</a>
    fontawesome_icon_name                 : thumbs-up

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
